<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Patient extends Model
{
    protected $table = 'injuryRegistry';
    protected $primaryKey = 'id';
    protected $fillable = ['firstName', 'middleName', 'lName','docAdmit', 'frstAid','natureOfInjury',
                        'rdoAid',
                        'abrasionCh',
                        'avulsionCh',
                        'burnCh',
                        'concussionCh',
                        'contusionCh',
                        'fractureCh',
                        'openTypeCh',
                        'closedTypeCh',
                        'woundCh',
                        'traumaCh',
                        'others1Ch',
                        'bitesCh',
                        'burnCh',
                        'burn1Ch',
                        'chemicalCh',
                        'sharpCh',
                        'drowningCh',
                        'others5Ch',
                        'natureCh',
                        'gunshotCh',
                        'hangingCh',
                        'maulingCh',
                        'transportCh',
                        'fallCh',
                        'firecrackerCh',
                        'assaultCh',
                        'noneCh',
                        'airbagCh',
                        'helmetCh',
                        'childseatCh',
                        'seatbeltCh',
                        'unknown5Ch',
                        'vestCh',
                        'others12Ch',
                        'alcoholCh',
                        'smokingCh',
                        'drugsCh',
                        'phoneCh',
                        'sleepyCh',
                        'others11Ch',
                        'unknown',
                        'injryRdo',
                        'otherRdo',
                        'transferRdo',
                        'referral',
                        'degreeRdoBtn',
                        'arrival',
                        'status',
                        'transpoRdo',
                        'transpoRdo1',
                        'outcome',
                        'drowningRdo',
                        'burnRdo',
                        'natureRdo',
                        'abrasion',
                        'avulsion',
                        'site',
                        'concussion',
                        'contusion',
                        'openType',
                        'closedType',
                        'wound',
                        'traumaticAmputation',
                        'others1',
                        'bites',
                        'others2',
                        'chemical',
                        'sharp',
                        'others3',
                        'others4',
                        'gunshot',
                        'fall',
                        'firecracker',
                        'others5',
                        'others6',
                        'others7',
                        'others8',
                        'withothers',
                        'others9',
                        'others10',
                        'others11',
                        'hospPhys',
                        'workplaceInput',
                        'impression',
                        'others12',
                        'others13',
                        'icdNature',
                        'icdExternal',
                        'treatment',
                        'treatment1',
                        'collRdo',
                        'dispoRdo',
                        'victimsRdo',
                        'severity',
                        'vehicleRdo',
                        'posRdo',
                        'placeRdo',
                        'activityRdo',
                        'transferred'];
    public function setNatureOfInjuryAttribute($value)
    {
        $this->attributes['natureOfInjury'] = json_encode($value);
    }

    public function getNatureOfInjuryAttribute($value)
    {
        return $this->attributes['natureOfInjury'] = json_decode($value);
    }
}
